author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Mail-Audit-Razor
no_index: 
  directory: 
    - inc
    - t
requires: 
  Mail::Audit: 2.217
  Razor::Agent: 0
  Razor::Client: 0
  Razor::String: 0
version: 1.801
